### ISSUE TITLE
Uploading CSV Parser Error

### ISSUE THREAD

**Issue by ashleevise** [EMN-Data/emn-sdk-docs#3]
Attached is the metadata file that I am trying to upload.
[LTE_data_metadata_template.xlsx](https://github.com/EMN-Data/emn-sdk-docs/files/5844968/LTE_data_metadata_template.xlsx)
 Python crashes and I get the following error:
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/gui/desktop/gui.py", line 501, in upload_action
    self.arch.create_dataset(ds_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/gui/desktop/gui.py", line 90, in create_dataset
    ckan.upload(package_id, use_existing=False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/ckan.py", line 133, in upload
    result = self._create_package(**create_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/ckan.py", line 157, in _create_package
    if "in use" in response["error"]["name"][0]:
KeyError: 'name'
[1]    51993 abort      emn ui`

which is different than the error that I was getting last week, Python did not crash but the file wasn't uploaded and this is the error that I received:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/gui/desktop/gui.py", line 507, in upload_action
    self.arch.upload_files(ds_name, upload_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/gui/desktop/gui.py", line 115, in upload_files
    records = parser.parse([file_or_dir])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/parsers/batch_parser.py", line 31, in parse
    record_list = parser.parse(fname)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/parsers/spreadsheet_parser.py", line 82, in parse
    records = self._dispatch()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/parsers/spreadsheet_parser.py", line 98, in _dispatch
    return self._parse_excel()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/parsers/spreadsheet_parser.py", line 109, in _parse_excel
    rec = self._parse_excel_sheet(workbook.sheet_by_index(i))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/parsers/spreadsheet_parser.py", line 118, in _parse_excel_sheet
    return self.parse_rows(rows)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/emn_sdk/io/parsers/spreadsheet_parser.py", line 186, in parse_rows
    raise ParseError(f"Cannot find data block with name '{derived_name}' "
emn_sdk.io.parser.ParseError: Cannot find data block with name '' matching derived search data block
Abort trap: 6`

**Comment by dangunter** [comment]
@ashleevise when you say "upload" you mean via the UI? While I'm trying to get to this, quick qn: did you put your API key in the config?

**Comment by ashleevise** [comment]
@dangunter Yes. I am able to upload different files fine. It seems like this error is occurring when it tries to parse the file. 

Excel file that I am trying to upload is now attached, it wasn't before sorry.

**Comment by dangunter** [comment]
@ashleevise moved to https://github.com/EMN-Data/emn-sdk/issues/102
